# Local Machine Configuration
model:
  architecture: "vnet"    # Model architecture for local machine
  in_channels: 4          # Number of input channels (modalities)
  out_channels: 5         # Number of output classes
  filters: [32, 64, 128]  # Adjust filters as needed
  roi: [96, 96, 96]       # Region of interest for sliding window inference

data:
  train_dir: "./data/BraTS2024-BraTS-GLI-TrainingData/training_data1_v2"   # Path to training data on local machine
  val_dir: "./data/BraTS2024-BraTS-GLI-ValidationData/validation_data"     # Path to validation data on local machine

training:
  batch_size: 1             # Batch size suitable for local machine memory capacity
  num_workers: 4            # Number of workers for DataLoader
  learning_rate: 0.0001     # Learning rate for the optimizer
  epochs: 5                 # Number of epochs for training
  seed: 42                  # Random seed for reproducibility
  checkpoint_dir: "./checkpoints"  # Directory to save checkpoints locally

# Azure Configuration
model:
  architecture: "segres_net"    # Model architecture for Azure
  in_channels: 4                # Number of input channels (modalities)
  out_channels: 5               # Number of output classes
  filters: [32, 64, 128]        # Filter sizes for the model layers
  roi: [96, 96, 96]             # Region of interest for sliding window inference

data:
  train_dir: "/mnt/batch/tasks/shared/LS_root/mounts/clusters/azureml-training/datasets/BraTS2024-BraTS-GLI-TrainingData/training_data1_v2"  # Azure blob storage path to training data
  val_dir: "/mnt/batch/tasks/shared/LS_root/mounts/clusters/azureml-training/datasets/BraTS2024-BraTS-GLI-ValidationData/validation_data"  # Azure blob storage path to validation data

training:
  batch_size: 4                 # Larger batch size for cloud environment
  num_workers: 4                # Number of workers for DataLoader
  learning_rate: 0.0001         # Learning rate for optimizer
  epochs: 5                     # Number of epochs for training
  seed: 42                      # Random seed for reproducibility
  checkpoint_dir: "/outputs/checkpoints"  # Directory to save checkpoints in Azure blob storage
